services:
  minio-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4950:4950"
    env_file:
      - .env
    restart: always
    networks:
      - minio_gateway_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  clamav-worker:
    build: .
    container_name: clamav-worker
    command: ["bun", "run", "worker.js"]
    env_file:
      - .env
    networks:
      - minio_gateway_network

networks:
  minio_gateway_network:
    driver: bridge
