sonar.projectKey=YOUR_APP_NAME
sonar.projectName=YOUR_APP_NAME

sonar.sources=YOUR_DIRECTORY
sonar.token=YOUR_TOKEN
sonar.sourceEncoding=UTF-8
sonar.host.url=YOUR_APP_PORT
sonar.typescript.tsconfigPath=tsconfig.json